version: '3'
services:

# mysql8 数据库
  mysql8:
    image: mysql:8
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    # restart: always
    environment:
      TZ: Asia/Shanghai # 指定时区
      MYSQL_ROOT_PASSWORD: "123456" # 配置root用户密码
      MYSQL_DATABASE: "cooltest" # 业务库名
      MYSQL_USER: "cooltest" # 业务库用户名
      MTSQL_PASSWORD: "123123" # 业务库密码
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql/:/var/lib/mysql/
  
# redis 数据库
  redis:
    image: redis
    # command: --requirepass "12345678" # redis库密码,不需要密码注释本行
    # restart: always
    environment:
      TZ: Asia/Shanghai # 指定时区
    volumes:
      - ./data/redis/:/data/
    ports:
      - 6379:6379