// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"cool-admin-go/internal/service/internal/dao/internal"
)

// baseSysUserRoleDao is the data access object for table base_sys_user_role.
// You can define custom methods on it to extend its functionality as you wish.
type baseSysUserRoleDao struct {
	*internal.BaseSysUserRoleDao
}

var (
	// BaseSysUserRole is globally public accessible object for table base_sys_user_role operations.
	BaseSysUserRole = baseSysUserRoleDao{
		internal.NewBaseSysUserRoleDao(),
	}
)

// Fill with you ideas below.
