// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"cool-admin-go/internal/service/internal/dao/internal"
)

// baseSysDepartmentDao is the data access object for table base_sys_department.
// You can define custom methods on it to extend its functionality as you wish.
type baseSysDepartmentDao struct {
	*internal.BaseSysDepartmentDao
}

var (
	// BaseSysDepartment is globally public accessible object for table base_sys_department operations.
	BaseSysDepartment = baseSysDepartmentDao{
		internal.NewBaseSysDepartmentDao(),
	}
)

// Fill with you ideas below.
