// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"cool-admin-go/internal/service/internal/dao/internal"
)

// baseSysConfDao is the data access object for table base_sys_conf.
// You can define custom methods on it to extend its functionality as you wish.
type baseSysConfDao struct {
	*internal.BaseSysConfDao
}

var (
	// BaseSysConf is globally public accessible object for table base_sys_conf operations.
	BaseSysConf = baseSysConfDao{
		internal.NewBaseSysConfDao(),
	}
)

// Fill with you ideas below.
