// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"cool-admin-go/internal/service/internal/dao/internal"
)

// baseSysLogDao is the data access object for table base_sys_log.
// You can define custom methods on it to extend its functionality as you wish.
type baseSysLogDao struct {
	*internal.BaseSysLogDao
}

var (
	// BaseSysLog is globally public accessible object for table base_sys_log operations.
	BaseSysLog = baseSysLogDao{
		internal.NewBaseSysLogDao(),
	}
)

// Fill with you ideas below.
