// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"cool-admin-go/internal/service/internal/dao/internal"
)

// baseSysRoleDepartmentDao is the data access object for table base_sys_role_department.
// You can define custom methods on it to extend its functionality as you wish.
type baseSysRoleDepartmentDao struct {
	*internal.BaseSysRoleDepartmentDao
}

var (
	// BaseSysRoleDepartment is globally public accessible object for table base_sys_role_department operations.
	BaseSysRoleDepartment = baseSysRoleDepartmentDao{
		internal.NewBaseSysRoleDepartmentDao(),
	}
)

// Fill with you ideas below.
