// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"cool-admin-go/internal/service/internal/dao/internal"
)

// baseSysRoleMenuDao is the data access object for table base_sys_role_menu.
// You can define custom methods on it to extend its functionality as you wish.
type baseSysRoleMenuDao struct {
	*internal.BaseSysRoleMenuDao
}

var (
	// BaseSysRoleMenu is globally public accessible object for table base_sys_role_menu operations.
	BaseSysRoleMenu = baseSysRoleMenuDao{
		internal.NewBaseSysRoleMenuDao(),
	}
)

// Fill with you ideas below.
