// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"cool-admin-go/internal/service/internal/dao/internal"
)

// baseSysParamDao is the data access object for table base_sys_param.
// You can define custom methods on it to extend its functionality as you wish.
type baseSysParamDao struct {
	*internal.BaseSysParamDao
}

var (
	// BaseSysParam is globally public accessible object for table base_sys_param operations.
	BaseSysParam = baseSysParamDao{
		internal.NewBaseSysParamDao(),
	}
)

// Fill with you ideas below.
