// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"cool-admin-go/internal/service/internal/dao/internal"
)

// baseSysUserDao is the data access object for table base_sys_user.
// You can define custom methods on it to extend its functionality as you wish.
type baseSysUserDao struct {
	*internal.BaseSysUserDao
}

var (
	// BaseSysUser is globally public accessible object for table base_sys_user operations.
	BaseSysUser = baseSysUserDao{
		internal.NewBaseSysUserDao(),
	}
)

// Fill with you ideas below.
