// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"cool-admin-go/internal/service/internal/dao/internal"
)

// demoGoodsDao is the data access object for table demo_goods.
// You can define custom methods on it to extend its functionality as you wish.
type demoGoodsDao struct {
	*internal.DemoGoodsDao
}

var (
	// DemoGoods is globally public accessible object for table demo_goods operations.
	DemoGoods = demoGoodsDao{
		internal.NewDemoGoodsDao(),
	}
)

// Fill with you ideas below.
