// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"cool-admin-go/internal/service/internal/dao/internal"
)

// spaceInfoDao is the data access object for table space_info.
// You can define custom methods on it to extend its functionality as you wish.
type spaceInfoDao struct {
	*internal.SpaceInfoDao
}

var (
	// SpaceInfo is globally public accessible object for table space_info operations.
	SpaceInfo = spaceInfoDao{
		internal.NewSpaceInfoDao(),
	}
)

// Fill with you ideas below.
