// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"cool-admin-go/internal/service/internal/dao/internal"
)

// taskLogDao is the data access object for table task_log.
// You can define custom methods on it to extend its functionality as you wish.
type taskLogDao struct {
	*internal.TaskLogDao
}

var (
	// TaskLog is globally public accessible object for table task_log operations.
	TaskLog = taskLogDao{
		internal.NewTaskLogDao(),
	}
)

// Fill with you ideas below.
