// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"cool-admin-go/internal/service/internal/dao/internal"
)

// taskInfoDao is the data access object for table task_info.
// You can define custom methods on it to extend its functionality as you wish.
type taskInfoDao struct {
	*internal.TaskInfoDao
}

var (
	// TaskInfo is globally public accessible object for table task_info operations.
	TaskInfo = taskInfoDao{
		internal.NewTaskInfoDao(),
	}
)

// Fill with you ideas below.
