// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// BaseSysRole is the golang structure of table base_sys_role for DAO operations like Where/Data.
type BaseSysRole struct {
	g.Meta     `orm:"table:base_sys_role, do:true"`
	Id         interface{} // ID
	CreateTime *gtime.Time // 创建时间
	UpdateTime *gtime.Time // 更新时间
	UserId     interface{} // 用户ID
	Name       interface{} // 名称
	Label      interface{} // 角色标签
	Remark     interface{} // 备注
	Relevance  interface{} // 数据权限是否关联上下级
}
