// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// BaseSysParam is the golang structure of table base_sys_param for DAO operations like Where/Data.
type BaseSysParam struct {
	g.Meta     `orm:"table:base_sys_param, do:true"`
	Id         interface{} // ID
	CreateTime *gtime.Time // 创建时间
	UpdateTime *gtime.Time // 更新时间
	KeyName    interface{} // 键位
	Name       interface{} // 名称
	Data       interface{} // 数据
	DataType   interface{} // 数据类型 0:字符串 1：数组 2：键值对
	Remark     interface{} // 备注
}
