// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// DemoGoods is the golang structure of table demo_goods for DAO operations like Where/Data.
type DemoGoods struct {
	g.Meta     `orm:"table:demo_goods, do:true"`
	Id         interface{} // ID
	CreateTime *gtime.Time // 创建时间
	UpdateTime *gtime.Time // 更新时间
	Title      interface{} // 标题
	Pic        interface{} // 图片
	Price      interface{} // 价格
	Type       interface{} // 分类
}
