// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SpaceType is the golang structure of table space_type for DAO operations like Where/Data.
type SpaceType struct {
	g.Meta     `orm:"table:space_type, do:true"`
	Id         interface{} // ID
	CreateTime *gtime.Time // 创建时间
	UpdateTime *gtime.Time // 更新时间
	Name       interface{} // 类别名称
	ParentId   interface{} // 父分类ID
}
