// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TaskLog is the golang structure of table task_log for DAO operations like Where/Data.
type TaskLog struct {
	g.Meta     `orm:"table:task_log, do:true"`
	Id         interface{} // ID
	CreateTime *gtime.Time // 创建时间
	UpdateTime *gtime.Time // 更新时间
	TaskId     interface{} // 任务ID
	Status     interface{} // 状态 0:失败 1：成功
	Detail     interface{} // 详情描述
}
