// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// TaskInfo is the golang structure of table task_info for DAO operations like Where/Data.
type TaskInfo struct {
	g.Meta      `orm:"table:task_info, do:true"`
	Id          interface{} // ID
	CreateTime  *gtime.Time // 创建时间
	UpdateTime  *gtime.Time // 更新时间
	JobId       interface{} // 任务ID
	RepeatConf  interface{} // 任务配置
	Name        interface{} // 名称
	Cron        interface{} // cron
	Limit       interface{} // 最大执行次数 不传为无限次
	Every       interface{} // 每间隔多少毫秒执行一次 如果cron设置了 这项设置就无效
	Remark      interface{} // 备注
	Status      interface{} // 状态 0:停止 1：运行
	StartDate   *gtime.Time // 开始时间
	EndDate     *gtime.Time // 结束时间
	Data        interface{} // 数据
	Service     interface{} // 执行的service实例ID
	Type        interface{} // 状态 0:系统 1：用户
	NextRunTime *gtime.Time // 下一次执行时间
	TaskType    interface{} // 状态 0:cron 1：时间间隔
}
