// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// BaseSysRoleMenu is the golang structure for table base_sys_role_menu.
type BaseSysRoleMenu struct {
	Id         int         `json:"id"         description:"ID"`
	CreateTime *gtime.Time `json:"createTime" description:"创建时间"`
	UpdateTime *gtime.Time `json:"updateTime" description:"更新时间"`
	RoleId     int64       `json:"roleId"     description:"角色ID"`
	MenuId     int64       `json:"menuId"     description:"菜单ID"`
}
