// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// BaseSysParam is the golang structure for table base_sys_param.
type BaseSysParam struct {
	Id         int         `json:"id"         description:"ID"`
	CreateTime *gtime.Time `json:"createTime" description:"创建时间"`
	UpdateTime *gtime.Time `json:"updateTime" description:"更新时间"`
	KeyName    string      `json:"keyName"    description:"键位"`
	Name       string      `json:"name"       description:"名称"`
	Data       string      `json:"data"       description:"数据"`
	DataType   int         `json:"dataType"   description:"数据类型 0:字符串 1：数组 2：键值对"`
	Remark     string      `json:"remark"     description:"备注"`
}
