// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// BaseSysUser is the golang structure for table base_sys_user.
type BaseSysUser struct {
	Id           int         `json:"id"           description:"ID"`
	CreateTime   *gtime.Time `json:"createTime"   description:"创建时间"`
	UpdateTime   *gtime.Time `json:"updateTime"   description:"更新时间"`
	DepartmentId int64       `json:"departmentId" description:"部门ID"`
	Name         string      `json:"name"         description:"姓名"`
	Username     string      `json:"username"     description:"用户名"`
	Password     string      `json:"password"     description:"密码"`
	PasswordV    int         `json:"passwordV"    description:"密码版本, 作用是改完密码，让原来的token失效"`
	NickName     string      `json:"nickName"     description:"昵称"`
	HeadImg      string      `json:"headImg"      description:"头像"`
	Phone        string      `json:"phone"        description:"手机"`
	Email        string      `json:"email"        description:"邮箱"`
	Status       int         `json:"status"       description:"状态 0:禁用 1：启用"`
	Remark       string      `json:"remark"       description:"备注"`
	SocketId     string      `json:"socketId"     description:"socketId"`
}
