// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// BaseSysMenu is the golang structure for table base_sys_menu.
type BaseSysMenu struct {
	Id         int         `json:"id"         description:"ID"`
	CreateTime *gtime.Time `json:"createTime" description:"创建时间"`
	UpdateTime *gtime.Time `json:"updateTime" description:"更新时间"`
	ParentId   int64       `json:"parentId"   description:"父菜单ID"`
	Name       string      `json:"name"       description:"菜单名称"`
	Router     string      `json:"router"     description:"菜单地址"`
	Perms      string      `json:"perms"      description:"权限标识"`
	Type       int         `json:"type"       description:"类型 0：目录 1：菜单 2：按钮"`
	Icon       string      `json:"icon"       description:"图标"`
	OrderNum   int         `json:"orderNum"   description:"排序"`
	ViewPath   string      `json:"viewPath"   description:"视图地址"`
	KeepAlive  int         `json:"keepAlive"  description:"路由缓存"`
	IsShow     int         `json:"isShow"     description:"父菜单名称"`
}
