// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// BaseSysLog is the golang structure for table base_sys_log.
type BaseSysLog struct {
	Id         int         `json:"id"         description:"ID"`
	CreateTime *gtime.Time `json:"createTime" description:"创建时间"`
	UpdateTime *gtime.Time `json:"updateTime" description:"更新时间"`
	UserId     int64       `json:"userId"     description:"用户ID"`
	Action     string      `json:"action"     description:"行为"`
	Ip         string      `json:"ip"         description:"ip"`
	IpAddr     string      `json:"ipAddr"     description:"ip地址"`
	Params     string      `json:"params"     description:"参数"`
}
