// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// BaseSysConf is the golang structure for table base_sys_conf.
type BaseSysConf struct {
	Id         int         `json:"id"         description:"ID"`
	CreateTime *gtime.Time `json:"createTime" description:"创建时间"`
	UpdateTime *gtime.Time `json:"updateTime" description:"更新时间"`
	CKey       string      `json:"cKey"       description:"配置键"`
	CValue     string      `json:"cValue"     description:"配置值"`
}
