// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// BaseSysRole is the golang structure for table base_sys_role.
type BaseSysRole struct {
	Id         int         `json:"id"         description:"ID"`
	CreateTime *gtime.Time `json:"createTime" description:"创建时间"`
	UpdateTime *gtime.Time `json:"updateTime" description:"更新时间"`
	UserId     string      `json:"userId"     description:"用户ID"`
	Name       string      `json:"name"       description:"名称"`
	Label      string      `json:"label"      description:"角色标签"`
	Remark     string      `json:"remark"     description:"备注"`
	Relevance  int         `json:"relevance"  description:"数据权限是否关联上下级"`
}
