// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// BaseSysUserRole is the golang structure for table base_sys_user_role.
type BaseSysUserRole struct {
	Id         int         `json:"id"         description:"ID"`
	CreateTime *gtime.Time `json:"createTime" description:"创建时间"`
	UpdateTime *gtime.Time `json:"updateTime" description:"更新时间"`
	UserId     int64       `json:"userId"     description:"用户ID"`
	RoleId     int64       `json:"roleId"     description:"角色ID"`
}
