// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// BaseSysDepartment is the golang structure for table base_sys_department.
type BaseSysDepartment struct {
	Id         int         `json:"id"         description:"ID"`
	CreateTime *gtime.Time `json:"createTime" description:"创建时间"`
	UpdateTime *gtime.Time `json:"updateTime" description:"更新时间"`
	Name       string      `json:"name"       description:"部门名称"`
	ParentId   int64       `json:"parentId"   description:"上级部门ID"`
	OrderNum   int         `json:"orderNum"   description:"排序"`
}
