// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// BaseSysRoleDepartment is the golang structure for table base_sys_role_department.
type BaseSysRoleDepartment struct {
	Id           int         `json:"id"           description:"ID"`
	CreateTime   *gtime.Time `json:"createTime"   description:"创建时间"`
	UpdateTime   *gtime.Time `json:"updateTime"   description:"更新时间"`
	RoleId       int64       `json:"roleId"       description:"角色ID"`
	DepartmentId int64       `json:"departmentId" description:"部门ID"`
}
