// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// DemoGoods is the golang structure for table demo_goods.
type DemoGoods struct {
	Id         int         `json:"id"         description:"ID"`
	CreateTime *gtime.Time `json:"createTime" description:"创建时间"`
	UpdateTime *gtime.Time `json:"updateTime" description:"更新时间"`
	Title      string      `json:"title"      description:"标题"`
	Pic        string      `json:"pic"        description:"图片"`
	Price      float64     `json:"price"      description:"价格"`
	Type       int         `json:"type"       description:"分类"`
}
