// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SpaceInfo is the golang structure for table space_info.
type SpaceInfo struct {
	Id         int         `json:"id"         description:"ID"`
	CreateTime *gtime.Time `json:"createTime" description:"创建时间"`
	UpdateTime *gtime.Time `json:"updateTime" description:"更新时间"`
	Url        string      `json:"url"        description:"地址"`
	Type       string      `json:"type"       description:"类型"`
	ClassifyId int64       `json:"classifyId" description:"分类ID"`
}
