// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// TaskLog is the golang structure for table task_log.
type TaskLog struct {
	Id         int         `json:"id"         description:"ID"`
	CreateTime *gtime.Time `json:"createTime" description:"创建时间"`
	UpdateTime *gtime.Time `json:"updateTime" description:"更新时间"`
	TaskId     int64       `json:"taskId"     description:"任务ID"`
	Status     int         `json:"status"     description:"状态 0:失败 1：成功"`
	Detail     string      `json:"detail"     description:"详情描述"`
}
