// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// TaskInfo is the golang structure for table task_info.
type TaskInfo struct {
	Id          int         `json:"id"          description:"ID"`
	CreateTime  *gtime.Time `json:"createTime"  description:"创建时间"`
	UpdateTime  *gtime.Time `json:"updateTime"  description:"更新时间"`
	JobId       string      `json:"jobId"       description:"任务ID"`
	RepeatConf  string      `json:"repeatConf"  description:"任务配置"`
	Name        string      `json:"name"        description:"名称"`
	Cron        string      `json:"cron"        description:"cron"`
	Limit       int         `json:"limit"       description:"最大执行次数 不传为无限次"`
	Every       int         `json:"every"       description:"每间隔多少毫秒执行一次 如果cron设置了 这项设置就无效"`
	Remark      string      `json:"remark"      description:"备注"`
	Status      int         `json:"status"      description:"状态 0:停止 1：运行"`
	StartDate   *gtime.Time `json:"startDate"   description:"开始时间"`
	EndDate     *gtime.Time `json:"endDate"     description:"结束时间"`
	Data        string      `json:"data"        description:"数据"`
	Service     string      `json:"service"     description:"执行的service实例ID"`
	Type        int         `json:"type"        description:"状态 0:系统 1：用户"`
	NextRunTime *gtime.Time `json:"nextRunTime" description:"下一次执行时间"`
	TaskType    int         `json:"taskType"    description:"状态 0:cron 1：时间间隔"`
}
