// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// BaseSysRoleDepartmentDao is the data access object for table base_sys_role_department.
type BaseSysRoleDepartmentDao struct {
	table   string                       // table is the underlying table name of the DAO.
	group   string                       // group is the database configuration group name of current DAO.
	columns BaseSysRoleDepartmentColumns // columns contains all the column names of Table for convenient usage.
}

// BaseSysRoleDepartmentColumns defines and stores column names for table base_sys_role_department.
type BaseSysRoleDepartmentColumns struct {
	Id           string // ID
	CreateTime   string // 创建时间
	UpdateTime   string // 更新时间
	RoleId       string // 角色ID
	DepartmentId string // 部门ID
}

//  baseSysRoleDepartmentColumns holds the columns for table base_sys_role_department.
var baseSysRoleDepartmentColumns = BaseSysRoleDepartmentColumns{
	Id:           "id",
	CreateTime:   "createTime",
	UpdateTime:   "updateTime",
	RoleId:       "roleId",
	DepartmentId: "departmentId",
}

// NewBaseSysRoleDepartmentDao creates and returns a new DAO object for table data access.
func NewBaseSysRoleDepartmentDao() *BaseSysRoleDepartmentDao {
	return &BaseSysRoleDepartmentDao{
		group:   "default",
		table:   "base_sys_role_department",
		columns: baseSysRoleDepartmentColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *BaseSysRoleDepartmentDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *BaseSysRoleDepartmentDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *BaseSysRoleDepartmentDao) Columns() BaseSysRoleDepartmentColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *BaseSysRoleDepartmentDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *BaseSysRoleDepartmentDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *BaseSysRoleDepartmentDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
