// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// BaseSysLogDao is the data access object for table base_sys_log.
type BaseSysLogDao struct {
	table   string            // table is the underlying table name of the DAO.
	group   string            // group is the database configuration group name of current DAO.
	columns BaseSysLogColumns // columns contains all the column names of Table for convenient usage.
}

// BaseSysLogColumns defines and stores column names for table base_sys_log.
type BaseSysLogColumns struct {
	Id         string // ID
	CreateTime string // 创建时间
	UpdateTime string // 更新时间
	UserId     string // 用户ID
	Action     string // 行为
	Ip         string // ip
	IpAddr     string // ip地址
	Params     string // 参数
}

//  baseSysLogColumns holds the columns for table base_sys_log.
var baseSysLogColumns = BaseSysLogColumns{
	Id:         "id",
	CreateTime: "createTime",
	UpdateTime: "updateTime",
	UserId:     "userId",
	Action:     "action",
	Ip:         "ip",
	IpAddr:     "ipAddr",
	Params:     "params",
}

// NewBaseSysLogDao creates and returns a new DAO object for table data access.
func NewBaseSysLogDao() *BaseSysLogDao {
	return &BaseSysLogDao{
		group:   "default",
		table:   "base_sys_log",
		columns: baseSysLogColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *BaseSysLogDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *BaseSysLogDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *BaseSysLogDao) Columns() BaseSysLogColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *BaseSysLogDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *BaseSysLogDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *BaseSysLogDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
