// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// DemoGoodsDao is the data access object for table demo_goods.
type DemoGoodsDao struct {
	table   string           // table is the underlying table name of the DAO.
	group   string           // group is the database configuration group name of current DAO.
	columns DemoGoodsColumns // columns contains all the column names of Table for convenient usage.
}

// DemoGoodsColumns defines and stores column names for table demo_goods.
type DemoGoodsColumns struct {
	Id         string // ID
	CreateTime string // 创建时间
	UpdateTime string // 更新时间
	Title      string // 标题
	Pic        string // 图片
	Price      string // 价格
	Type       string // 分类
}

//  demoGoodsColumns holds the columns for table demo_goods.
var demoGoodsColumns = DemoGoodsColumns{
	Id:         "id",
	CreateTime: "createTime",
	UpdateTime: "updateTime",
	Title:      "title",
	Pic:        "pic",
	Price:      "price",
	Type:       "type",
}

// NewDemoGoodsDao creates and returns a new DAO object for table data access.
func NewDemoGoodsDao() *DemoGoodsDao {
	return &DemoGoodsDao{
		group:   "default",
		table:   "demo_goods",
		columns: demoGoodsColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *DemoGoodsDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *DemoGoodsDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *DemoGoodsDao) Columns() DemoGoodsColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *DemoGoodsDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *DemoGoodsDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *DemoGoodsDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
