// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SpaceInfoDao is the data access object for table space_info.
type SpaceInfoDao struct {
	table   string           // table is the underlying table name of the DAO.
	group   string           // group is the database configuration group name of current DAO.
	columns SpaceInfoColumns // columns contains all the column names of Table for convenient usage.
}

// SpaceInfoColumns defines and stores column names for table space_info.
type SpaceInfoColumns struct {
	Id         string // ID
	CreateTime string // 创建时间
	UpdateTime string // 更新时间
	Url        string // 地址
	Type       string // 类型
	ClassifyId string // 分类ID
}

//  spaceInfoColumns holds the columns for table space_info.
var spaceInfoColumns = SpaceInfoColumns{
	Id:         "id",
	CreateTime: "createTime",
	UpdateTime: "updateTime",
	Url:        "url",
	Type:       "type",
	ClassifyId: "classifyId",
}

// NewSpaceInfoDao creates and returns a new DAO object for table data access.
func NewSpaceInfoDao() *SpaceInfoDao {
	return &SpaceInfoDao{
		group:   "default",
		table:   "space_info",
		columns: spaceInfoColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SpaceInfoDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SpaceInfoDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *SpaceInfoDao) Columns() SpaceInfoColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *SpaceInfoDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SpaceInfoDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SpaceInfoDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
